Repository LASY-org/lasy, pull requests merged in 2023-10, with the labels that each got.

#184 Remove warnings in the documentation
  README.md
  docs/source/index.rst
Labels: documentation

#188 openPMD write: close file
  lasy/utils/openpmd_output.py
Labels: cleaning

#193 Show import path in the documentation
  docs/source/api/profiles/combined_profile.rst
  docs/source/api/profiles/from_array_profile.rst
  docs/source/api/profiles/from_openpmd_profile.rst
  docs/source/api/profiles/gaussian.rst
  docs/source/api/profiles/longitudinal/gaussian.rst
  docs/source/api/profiles/longitudinal/longitudinal_profile_from_data.rst
  docs/source/api/profiles/transverse/gaussian.rst
  docs/source/api/profiles/transverse/hermite_gaussian_profile.rst
  docs/source/api/profiles/transverse/jinc_profile.rst
  docs/source/api/profiles/transverse/laguerre_gaussian_profile.rst
  docs/source/api/profiles/transverse/super_gaussian_profile.rst
  docs/source/api/profiles/transverse/transverse_profile_from_data.rst
  docs/source/conf.py
Labels: documentation

#195 Fix cross-references to classes in Sphinx doc
  lasy/profiles/combined_profile.py
  lasy/profiles/longitudinal/gaussian_profile.py
  lasy/profiles/transverse/gaussian_profile.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/laguerre_gaussian_profile.py
Labels: bug, documentation
