Repository LASY-org/lasy, pull requests merged in 2023-04, with the labels that each got.

#114 Add time axis refinements to get_full_field method
  lasy/laser.py
  lasy/utils/laser_utils.py
Labels: new feature

#125 make lasy comply with openPMD-standard laser extension
  lasy/utils/openpmd_output.py
Labels: standard

#117 Improve Documentation Content
  docs/source/api/profiles/transverse/index.rst
  docs/source/api/profiles/transverse/jinc_profile.rst
  docs/source/api/profiles/transverse/transverse_profile_from_data.rst
  docs/source/code_overview/codes_supporting_lasy.rst
  docs/source/code_overview/index.rst
  docs/source/index.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/local_machine_install.rst
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/jinc_profile.py
  lasy/profiles/transverse/transverse_profile_from_data.py
Labels: documentation

#131 Add version number for lasy
  lasy/__init__.py
  setup.py
Labels: documentation

#120 Pre-Commit: pydocstyle
  .pre-commit-config.yaml
  lasy/laser.py
  lasy/profiles/combined_profile.py
  lasy/profiles/gaussian_profile.py
  lasy/profiles/longitudinal/gaussian_profile.py
  lasy/profiles/longitudinal/longitudinal_profile.py
  lasy/profiles/profile.py
  lasy/profiles/transverse/gaussian_profile.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/jinc_profile.py
  lasy/profiles/transverse/laguerre_gaussian_profile.py
  lasy/profiles/transverse/super_gaussian_profile.py
  lasy/profiles/transverse/transverse_profile.py
  lasy/profiles/transverse/transverse_profile_from_data.py
  lasy/utils/box.py
  lasy/utils/exp_data_utils.py
  lasy/utils/grid.py
  lasy/utils/laser_utils.py
  lasy/utils/mode_decomposition.py
  lasy/utils/openpmd_output.py
  pyproject.toml
Labels: documentation
