Repository LASY-org/lasy, pull requests merged in 2023-08, with the labels that each got.

#151 Profile from openPMD file
  docs/source/api/profiles/from_openpmd_profile.rst
  docs/source/api/profiles/index.rst
  lasy/profiles/__init__.py
  lasy/profiles/from_openpmd_profile.py
  requirements.txt
Labels: new feature

#158 Improvements in the reader from openPMD file
  lasy/laser.py
  lasy/profiles/from_array_profile.py
  lasy/profiles/from_openpmd_profile.py
  lasy/utils/grid.py
  lasy/utils/laser_utils.py
  lasy/utils/openpmd_output.py
  requirements.txt
  tests/test_laser_profiles.py
Labels: new feature, standard

#169 Update docs to use `sphinx_design`
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation, cleaning

#171 Conform to the new openPMD standard
  lasy/utils/openpmd_output.py
Labels: standard

#172 Zenodo File
  .zenodo.json
Labels: documentation
