Repository LASY-org/lasy, pull requests merged in 2023-02, with the labels that each got.

#87 Merge `hackathon` branch into `development`
  .github/workflows/unix.yml
  README.md
  conda.yml
  examples/lasy_propagator_test.py
  lasy/laser.py
  lasy/profiles/combined_profile.py
  lasy/profiles/gaussian_profile.py
  lasy/profiles/longitudinal/gaussian_profile.py
  lasy/profiles/longitudinal/longitudinal_profile.py
  lasy/profiles/profile.py
  lasy/profiles/transverse/gaussian_profile.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/laguerre_gaussian_profile.py
  lasy/profiles/transverse/transverse_profile.py
  lasy/utils/laser_utils.py
  requirements.txt
  setup.py
  tests/requirements.txt
  tests/test_laser_profiles.py
Labels: hackathon

#95 Install pre-commit
  .pre-commit-config.yaml
  docs/source/api/profiles/index.rst
  docs/source/index.rst
Labels: CI

#96 Make energy calibration the default
  .gitignore
  lasy/laser.py
Labels: hackathon

#101 Add missing documentation requirement
  docs/requirements.txt
Labels: hackathon

#100 Populate __init__ to simplify imports
  examples/test.py
  lasy/profiles/__init__.py
  lasy/profiles/gaussian_profile.py
  lasy/profiles/longitudinal/__init__.py
  lasy/profiles/transverse/__init__.py
  tests/test_laser_profiles.py
Labels: cleaning

#97 Add transverse laser from data and offset profile functionality
  lasy/profiles/transverse/gaussian_profile.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/laguerre_gaussian_profile.py
  lasy/profiles/transverse/super_gaussian_profile.py
  lasy/profiles/transverse/transverse_profile.py
  lasy/profiles/transverse/transverse_profile_from_data.py
  lasy/utils/exp_data_utils.py
Labels: hackathon

#106 Explicitly import scipy constants
  lasy/utils/laser_utils.py
Labels: hackathon
