Repository LASY-org/lasy, pull requests merged in 2023-05, with the labels that each got.

#135 set axiprop to be installed from pip
  requirements.txt
Labels: cleaning

#136 RTD Build: Latest Ubuntu
  .readthedocs.yaml
Labels: bug, documentation

#134 Markdown Readme: LaTeX Fix
  README.md
Labels: bug, documentation

#133 Set Version in Documentation
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#137 Version: 0.1.1
  lasy/__init__.py
Labels: documentation

#130 Adding an experimentally measured temporal pulse profile
  docs/source/api/profiles/longitudinal/index.rst
  docs/source/api/profiles/longitudinal/longitudinal_profile_from_data.rst
  lasy/profiles/longitudinal/__init__.py
  lasy/profiles/longitudinal/longitudinal_profile_from_data.py
Labels: new feature
