Repository LASY-org/lasy, pull requests merged in 2024-04, with the labels that each got.

#221 add speckled lasers to LASY
  docs/source/api/profiles/index.rst
  docs/source/api/profiles/speckled.rst
  lasy/profiles/__init__.py
  lasy/profiles/speckle_profile.py
  tests/test_laser_profiles.py
  tests/test_speckles.py
Labels: new feature

#235 CI: `isort` + `black` compatibility
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI

#243 Do not mention "Derived class" in the documentation
  lasy/profiles/gaussian_profile.py
  lasy/profiles/longitudinal/cosine_profile.py
  lasy/profiles/longitudinal/gaussian_profile.py
  lasy/profiles/longitudinal/longitudinal_profile_from_data.py
  lasy/profiles/longitudinal/super_gaussian_profile.py
  lasy/profiles/speckle_profile.py
  lasy/profiles/transverse/gaussian_profile.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/jinc_profile.py
  lasy/profiles/transverse/laguerre_gaussian_profile.py
  lasy/profiles/transverse/super_gaussian_profile.py
  lasy/profiles/transverse/transverse_profile.py
  lasy/profiles/transverse/transverse_profile_from_data.py
Labels: documentation
