Repository LASY-org/lasy, pull requests merged in 2024-07, with the labels that each got.

#239 A fix to prevent division by zero during normalization
  lasy/utils/laser_utils.py
Labels: bug

#199 Add thin optical elements in `lasy`
  docs/source/api/index.rst
  docs/source/api/optical_elements/index.rst
  docs/source/api/optical_elements/parabolic_mirror.rst
  lasy/laser.py
  lasy/optical_elements/__init__.py
  lasy/optical_elements/optical_element.py
  lasy/optical_elements/parabolic_mirror.py
  tests/test_parabolic_mirror.py
Labels: new feature

#242 CI: Pre-Commit `isort`
  .pre-commit-config.yaml
  docs/source/conf.py
  examples/example_gerchberg_saxton_algo.py
  examples/example_modal_decomposition_data.py
  lasy/laser.py
  lasy/optical_elements/parabolic_mirror.py
  lasy/profiles/__init__.py
  lasy/profiles/from_array_profile.py
  lasy/profiles/from_insight_file.py
  lasy/profiles/from_openpmd_profile.py
  lasy/profiles/longitudinal/__init__.py
  lasy/profiles/transverse/__init__.py
  lasy/profiles/transverse/hermite_gaussian_profile.py
  lasy/profiles/transverse/jinc_profile.py
  lasy/profiles/transverse/transverse_profile_from_data.py
  lasy/utils/laser_utils.py
  lasy/utils/mode_decomposition.py
  lasy/utils/openpmd_output.py
  lasy/utils/phase_retrieval.py
  lasy/utils/zernike.py
  setup.py
  tests/test_gaussian_propagator.py
  tests/test_gsalgo.py
  tests/test_laser_profiles.py
  tests/test_laser_utils.py
  tests/test_parabolic_mirror.py
  tests/test_speckles.py
  tests/test_t2z2t.py
Labels: CI

#248 [mini] Add assert in longitudinal profile from data
  lasy/profiles/longitudinal/longitudinal_profile_from_data.py
Labels: documentation
