Repository LASY-org/lasy, pull requests merged in 2024-08, with the labels that each got.

#274 [mini] fix docs compilation instructions in readme
  README.md
Labels: documentation

#280 CI: Ruff
  .pre-commit-config.yaml
  docs/source/tutorials/axiparabola.ipynb
  docs/source/tutorials/gaussian_laser.ipynb
  lasy/laser.py
  lasy/profiles/from_insight_file.py
  lasy/profiles/gaussian_profile.py
  lasy/profiles/speckle_profile.py
  lasy/utils/phase_retrieval.py
  lasy/utils/zernike.py
  pyproject.toml
  tests/test_axiparabola.py
  tests/test_laser_profiles.py
  tests/test_parabolic_mirror.py
  tests/test_polynomial_spectral_phase.py
  tests/test_speckles.py
Labels: cleaning, CI

#287 Pre-Commit: Ruff on All
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI

#275 Update documentation to discuss sum of profiles
  docs/source/api/profiles/index.rst
  docs/source/api/profiles/transverse/index.rst
  lasy/profiles/__init__.py
  lasy/profiles/profile.py
  lasy/profiles/transverse/transverse_profile.py
Labels: documentation
