Repository LASY-org/lasy, pull requests merged in 2025-05, with the labels that each got.

#418 [mini] Store position separately
  lasy/laser.py
  lasy/profiles/from_openpmd_profile.py
  lasy/utils/grid.py
  lasy/utils/laser_utils.py
  lasy/utils/openpmd_helper.py
Labels: design, standard, non-backward-compatible

#411 Structure for new propagators
  docs/source/api/index.rst
  docs/source/api/propagators/axiprop_propagators.rst
  docs/source/api/propagators/collins_sfft_propagator.rst
  docs/source/api/propagators/index.rst
  docs/source/api/propagators/propagator.rst
  docs/source/api/propagators/single_fft_propagator.rst
  lasy/laser.py
  lasy/propagators/__init__.py
  lasy/propagators/axiprop_propagators.py
  lasy/propagators/collins_sfft_propagator.py
  lasy/propagators/fresnel_sfft_propagator.py
  lasy/propagators/propagator.py
  lasy/propagators/single_fft_propagator.py
  lasy/utils/fft_wrapper.py
  lasy/utils/grid.py
  lasy/utils/phase_retrieval.py
  requirements.txt
  tests/test_laser_profiles.py
  tests/test_resampling.py
Labels: design, new feature

#421 Implement `AngularSpectrumDFFTPropagator` and `NonlinearKerrStep`
  docs/source/api/propagators/angular_spectrum_propagator.rst
  docs/source/api/propagators/index.rst
  docs/source/api/propagators/nonlinear_phase_shift.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/nonlinear_propagation_split_step.ipynb
  lasy/propagators/__init__.py
  lasy/propagators/angular_spectrum_propagator.py
  lasy/propagators/nonlinear_phase_shift.py
  lasy/utils/laser_utils.py
  tests/test_angular_spectrum_propagator.py
  tests/test_spm.py
Labels: new feature

#422 typo in the doc string
  lasy/laser.py
Labels: documentation

#423 fix argument order in axiprop fresnel propagator
  lasy/propagators/axiprop_propagators.py
Labels: bug

#427 [mini] make split step tutorial second order in time
  docs/source/tutorials/nonlinear_propagation_split_step.ipynb
Labels: documentation

#429 Fix propagator issue
  lasy/propagators/angular_spectrum_propagator.py
  lasy/utils/fft_wrapper.py
  lasy/utils/grid.py
Labels: bug, design
