Repository LASY-org/lasy, pull requests merged in 2025-04, with the labels that each got.

#388 [mini] Fix issue with flipped spectrum
  lasy/profiles/longitudinal/longitudinal_profile_from_data.py
Labels: bug

#383 Fix for issue #377: Fixed `grid.get_spectral_field()` and `get_phi2()`, added `get_spectral_phase()` and `get_gdd()` to laser_utils
  lasy/profiles/gaussian_profile.py
  lasy/utils/grid.py
  lasy/utils/laser_utils.py
  tests/test_STC.py
Labels: bug, cleaning

#390 [almost mini] More consistant handling of omega axis
  lasy/laser.py
  lasy/utils/grid.py
  lasy/utils/laser_utils.py
Labels: design, cleaning

#335 update show function to include intensity
  lasy/laser.py
  lasy/utils/plotting.py
  requirements.txt
Labels: design

#405 Fix bug in openPMD reader when extracting central frequency
  lasy/profiles/from_openpmd_profile.py
  lasy/utils/laser_utils.py
Labels: bug
